/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleSearchRouteImport } from './routes/$locale.search'
import { Route as LocaleProjectsRouteImport } from './routes/$locale.projects'
import { Route as LocaleEditorRouteImport } from './routes/$locale.editor'
import { Route as LocaleSectionSlugRouteImport } from './routes/$locale.$section.$slug'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSearchRoute = LocaleSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProjectsRoute = LocaleProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEditorRoute = LocaleEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSectionSlugRoute = LocaleSectionSlugRouteImport.update({
  id: '/$section/$slug',
  path: '/$section/$slug',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/editor': typeof LocaleEditorRoute
  '/$locale/projects': typeof LocaleProjectsRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$section/$slug': typeof LocaleSectionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/editor': typeof LocaleEditorRoute
  '/$locale/projects': typeof LocaleProjectsRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$section/$slug': typeof LocaleSectionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/editor': typeof LocaleEditorRoute
  '/$locale/projects': typeof LocaleProjectsRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$section/$slug': typeof LocaleSectionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/editor'
    | '/$locale/projects'
    | '/$locale/search'
    | '/$locale/'
    | '/$locale/$section/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/editor'
    | '/$locale/projects'
    | '/$locale/search'
    | '/$locale'
    | '/$locale/$section/$slug'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/editor'
    | '/$locale/projects'
    | '/$locale/search'
    | '/$locale/'
    | '/$locale/$section/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/search': {
      id: '/$locale/search'
      path: '/search'
      fullPath: '/$locale/search'
      preLoaderRoute: typeof LocaleSearchRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/projects': {
      id: '/$locale/projects'
      path: '/projects'
      fullPath: '/$locale/projects'
      preLoaderRoute: typeof LocaleProjectsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/editor': {
      id: '/$locale/editor'
      path: '/editor'
      fullPath: '/$locale/editor'
      preLoaderRoute: typeof LocaleEditorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/$section/$slug': {
      id: '/$locale/$section/$slug'
      path: '/$section/$slug'
      fullPath: '/$locale/$section/$slug'
      preLoaderRoute: typeof LocaleSectionSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleEditorRoute: typeof LocaleEditorRoute
  LocaleProjectsRoute: typeof LocaleProjectsRoute
  LocaleSearchRoute: typeof LocaleSearchRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleSectionSlugRoute: typeof LocaleSectionSlugRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleEditorRoute: LocaleEditorRoute,
  LocaleProjectsRoute: LocaleProjectsRoute,
  LocaleSearchRoute: LocaleSearchRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleSectionSlugRoute: LocaleSectionSlugRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
